ALTER TABLE ENROLL ADD CONSTRAINT fk_student FOREIGN KEY(student_ID) REFERENCES STUDENT(student_ID) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE ENROLL ADD CONSTRAINT fk_course FOREIGN KEY(course_ID) REFERENCES COURSE(course_ID) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE TEACHES ADD CONSTRAINT course_fk FOREIGN KEY(course_ID) REFERENCES COURSE(course_ID) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE TEACHES ADD CONSTRAINT fk_instructor FOREIGN KEY(instructor_ID) REFERENCES INSTRUCTOR(instructor_ID) ON DELETE CASCADE ON UPDATE CASCADE;