CREATE TABLE STUDENT (student_ID CHAR(5), Fname VARCHAR(20), Mname VARCHAR(20), Lname VARCHAR(20), CONSTRAINT pk_Student PRIMARY KEY (student_ID));
CREATE TABLE COURSE (course_ID CHAR(1), course_Name VARCHAR(20), CONSTRAINT pk_Course PRIMARY KEY (course_ID));
CREATE TABLE ENROLL (id INT, student_ID CHAR(5), course_ID CHAR(1), CONSTRAINT pk_SC PRIMARY KEY (id));
CREATE TABLE INSTRUCTOR (instructor_ID INT, Fname VARCHAR(20), Lname VARCHAR(20), CONSTRAINT pk_Instructor PRIMARY KEY (instructor_ID));
CREATE TABLE TEACHES (id INT, instructor_ID INT, course_ID CHAR(1), CONSTRAINT pk_IC PRIMARY KEY (id));